//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPBrowser.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SPBrowser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\n\nIt&apos;s likely you are missing the {1}. After download and install restart the {2}.\n\nWould you like to download the {1}?.
        /// </summary>
        internal static string ErrorMissingAssemblySDK {
            get {
                return ResourceManager.GetString("ErrorMissingAssemblySDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sharepointfoundation16.png.
        /// </summary>
        internal static string IMAGE_SITE {
            get {
                return ResourceManager.GetString("IMAGE_SITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workflows2.png.
        /// </summary>
        internal static string IMAGE_WORKFLOW_TEMPLATE {
            get {
                return ResourceManager.GetString("IMAGE_WORKFLOW_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MSDN {
            get {
                object obj = ResourceManager.GetObject("MSDN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Office365 {
            get {
                object obj = ResourceManager.GetObject("Office365", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office365_32x32 {
            get {
                object obj = ResourceManager.GetObject("Office365_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PowerShell {
            get {
                object obj = ResourceManager.GetObject("PowerShell", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Refresh {
            get {
                object obj = ResourceManager.GetObject("Refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint 2013 Client Browser v1.9, released: 03/21/2016
        /// - Fixed support for high-DPI display settings (http://spcb.codeplex.com/workitem/63851) and (http://spcb.codeplex.com/workitem/65006)
        ///
        ///SharePoint 2013 Client Browser v1.8, released: 02/15/2016
        /// - Added support for Fields, FieldLinks and Workflow Associations to Content Type node
        /// - Added Raw Data (tab) support for User Profile Properties
        /// - Added count of child nodes to Attachments, Fields values, Web Parts and File Versions
        /// - Added support  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReleaseNotes15_0 {
            get {
                return ResourceManager.GetString("ReleaseNotes15_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint Online Client Browser v2.3, released: xx/xx/2016
        /// - Fixed loading external users, only showed first external user. Now displays first 50 external users.
        ///
        ///SharePoint Online Client Browser v2.2, released: 03/21/2016
        /// - Fixed support for high-DPI display settings (http://spcb.codeplex.com/workitem/63851) and (http://spcb.codeplex.com/workitem/65006)
        ///
        ///SharePoint Online Client Browser v2.1, released: 02/15/2016
        /// - Added support for Fields, FieldLinks and Workflow Associations to Content Type no [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReleaseNotes16_0 {
            get {
                return ResourceManager.GetString("ReleaseNotes16_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint 2016 Client Browser v3.0, released: xx/xx/2017
        /// - Initial release for SharePoint Server 2016..
        /// </summary>
        internal static string ReleaseNotes16_1 {
            get {
                return ResourceManager.GetString("ReleaseNotes16_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Settings {
            get {
                object obj = ResourceManager.GetObject("Settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SharePoint {
            get {
                object obj = ResourceManager.GetObject("SharePoint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon SharePoint2013 {
            get {
                object obj = ResourceManager.GetObject("SharePoint2013", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sitelaunchsharedanonymously {
            get {
                object obj = ResourceManager.GetObject("sitelaunchsharedanonymously", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SplashScreenOffice365 {
            get {
                object obj = ResourceManager.GetObject("SplashScreenOffice365", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SplashScreenSharePoint2013 {
            get {
                object obj = ResourceManager.GetObject("SplashScreenSharePoint2013", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Warning {
            get {
                object obj = ResourceManager.GetObject("Warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
